# values.yaml
#
# This file contains values for variables referenced from yaml files in the templates directory.
#
# For further information on Helm templating see the documentation at:
#   https://helm.sh/docs/chart_template_guide/values_files/
#
# For an explanation of Redpanda configuration values:
#   https://vectorized.io/docs/advanced-configuration/

replicaCount: 3

image:
  repository: vectorized/redpanda
  # The imagePullPolicy will default to Always when the tag is 'latest'
  tag: latest

config:
  config_file: /etc/redpanda/redpanda.yaml
  license_key: ""
  organization: ""
  redpanda:
    admin:
      address: 0.0.0.0
      port: 9644
    advertised_kafka_api:
      address: 0.0.0.0
      port: 9092
    advertised_rpc_api:
      address: 0.0.0.0
      port: 33145
    auto_create_topics_enabled: true
    data_directory: /var/lib/redpanda/data
    developer_mode: false
    kafka_api:
      address: 0.0.0.0
      port: 9092
    kafka_api_tls:
      cert_file: ""
      enabled: false
      key_file: ""
      truststore_file: ""
    node_id: 0
    rpc_server:
      address: 0.0.0.0
      port: 33145
  rpk:
    coredump_dir: /var/lib/redpanda/coredump
    enable_memory_locking: false
    enable_usage_stats: true
    overprovisioned: false
    smp: 1
    tls:
      cert_file: ""
      key_file: ""
      truststore_file: ""
    tune_aio_events: false
    tune_clocksource: false
    tune_coredump: false
    tune_cpu: false
    tune_disk_irq: false
  seastar:
    default_log_level: info

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# It is highly recommended to use integer values for cpu
resources:
  requests:
    cpu: 1
    memory: 3Gi
  limits:
    cpu: 1
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - redpanda
          topologyKey: kubernetes.io/hostname

pdb:
  enabled: true
  maxUnavailable: 1
  minAvailable:
